language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements2.txt
  - pip install -e git://github.com/jmason86/python_convenience_functions#egg=jpm_logger
# command to run tests
script:
  - python -m pytest
